### ISSUE TITLE
Small typos in doc example file apply_detector.py

### ISSUE THREAD

**Issue by DBazin** [ATTPC/attpc_engine#24]
Just some typos on the paths in these two lines:
input_path = "output/kinematics/c16dd_d2_300Torr_184MeV.h5"
output_path = Path("output/detector/run_0001.h5")

should be:
input_path = "./output/kinematics/c16dd_d2_300Torr_184MeV.h5"
output_path = Path("./output/detector")

**Comment by gwm17** [comment]
Whoops hahaha, that is a very silly typo!

**Comment by gwm17** [comment]
Done in v0.1.6
