### ISSUE TITLE
Kinematics generator slows down for many events

### ISSUE THREAD

**Issue by sigmanotation** [ATTPC/attpc_engine#40]
The kinematics generator seems to considerably slow down when generating many events. In my testing, the speed seems to decrease around 1.4 million events. The decrease is significant, often saying it will take an hour or more to finish these last 100,000 events compared to the minutes it took before. The output file is fine, though.

**Comment by gwm17** [comment]
Verified on Ubuntu 22.04 with Python 3.11. Memory profiling indicates it is not a memory leak. My guess is that this is an HDF5 issue, maybe a limit on the total number of keys for reasonable performance.

**Comment by gwm17** [comment]
Definitely a key/metadata issue in HDF5. Fixed by simply splitting the events into 1,000,000 event sub-groups. Will be fixed for next release.
